// Code generated by "stringer -type Status -linecomment"; DO NOT EDIT.

package adbc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusOK-0]
	_ = x[StatusUnknown-1]
	_ = x[StatusNotImplemented-2]
	_ = x[StatusNotFound-3]
	_ = x[StatusAlreadyExists-4]
	_ = x[StatusInvalidArgument-5]
	_ = x[StatusInvalidState-6]
	_ = x[StatusInvalidData-7]
	_ = x[StatusIntegrity-8]
	_ = x[StatusInternal-9]
	_ = x[StatusIO-10]
	_ = x[StatusCancelled-11]
	_ = x[StatusTimeout-12]
	_ = x[StatusUnauthenticated-13]
	_ = x[StatusUnauthorized-14]
}

const _Status_name = "OKUnknownNot ImplementedNot FoundAlready ExistsInvalid ArgumentInvalid StateInvalid DataIntegrity IssueInternalI/OCancelledTimeoutUnauthenticatedUnauthorized"

var _Status_index = [...]uint8{0, 2, 9, 24, 33, 47, 63, 76, 88, 103, 111, 114, 123, 130, 145, 157}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
