/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeAdbcConnection {
  createStatement(): Promise<unknown>
  setOption(key: string, value: string): void
  getObjects(opts: GetObjectsOptions): Promise<unknown>
  getTableSchema(opts: GetTableSchemaOptions): Promise<unknown>
  getTableTypes(): Promise<unknown>
  getInfo(infoCodes?: Array<number> | undefined | null): Promise<unknown>
  commit(): Promise<unknown>
  rollback(): Promise<unknown>
  close(): void
}
export type _NativeAdbcConnection = NativeAdbcConnection

export declare class NativeAdbcDatabase {
  constructor(opts: ConnectOptions)
  connect(options?: Record<string, string> | undefined | null): Promise<unknown>
  close(): void
}
export type _NativeAdbcDatabase = NativeAdbcDatabase

export declare class NativeAdbcResultIterator {
  next(): Promise<unknown>
  close(): void
}
export type _NativeAdbcResultIterator = NativeAdbcResultIterator

export declare class NativeAdbcStatement {
  setSqlQuery(query: string): void
  setOption(key: string, value: string): void
  executeQuery(): Promise<unknown>
  executeUpdate(): Promise<unknown>
  bind(data: Buffer): Promise<unknown>
  startBindStreamExecute(schemaBytes: Buffer): Promise<unknown>
  startBindStream(schemaBytes: Buffer): Promise<unknown>
  pushBatch(data: Buffer): void
  endStream(): void
  close(): void
}
export type _NativeAdbcStatement = NativeAdbcStatement

export interface ConnectOptions {
  driver: string
  entrypoint?: string
  manifestSearchPaths?: Array<string>
  profileSearchPaths?: Array<string>
  loadFlags?: number
  databaseOptions?: Record<string, string>
}

export declare function crateVersion(): string

export declare function defaultAdbcVersion(): string

export declare function defaultLoadFlags(): number

export interface GetObjectsOptions {
  depth: number
  catalog?: string
  dbSchema?: string
  tableName?: string
  tableType?: Array<string>
  columnName?: string
}

export interface GetTableSchemaOptions {
  catalog?: string
  dbSchema?: string
  tableName: string
}
