// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include <stdlib.h>
#include "../../drivermgr/adbc.h"

struct AdbcError* ClickHouseErrorFromArrayStream(struct ArrowArrayStream*,
                                                 AdbcStatusCode*);
AdbcStatusCode ClickHouseDatabaseGetOption(struct AdbcDatabase*, const char*, char*,
                                           size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseGetOptionBytes(struct AdbcDatabase*, const char*,
                                                uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseGetOptionDouble(struct AdbcDatabase*, const char*,
                                                 double*, struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseGetOptionInt(struct AdbcDatabase*, const char*, int64_t*,
                                              struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode ClickHouseDatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode ClickHouseDatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode ClickHouseDatabaseSetOption(struct AdbcDatabase* db, const char* key,
                                           const char* value, struct AdbcError* err);
AdbcStatusCode ClickHouseDatabaseSetOptionBytes(struct AdbcDatabase*, const char*,
                                                const uint8_t*, size_t,
                                                struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseSetOptionDouble(struct AdbcDatabase*, const char*,
                                                 double, struct AdbcError*);
AdbcStatusCode ClickHouseDatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t,
                                              struct AdbcError*);

AdbcStatusCode ClickHouseConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionCommit(struct AdbcConnection* cnxn,
                                          struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionGetInfo(struct AdbcConnection* cnxn,
                                           const uint32_t* codes, size_t len,
                                           struct ArrowArrayStream* out,
                                           struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionGetObjects(
    struct AdbcConnection* cnxn, int depth, const char* catalog, const char* dbSchema,
    const char* tableName, const char** tableType, const char* columnName,
    struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionGetOption(struct AdbcConnection*, const char*, char*,
                                             size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetOptionBytes(struct AdbcConnection*, const char*,
                                                  uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetOptionDouble(struct AdbcConnection*, const char*,
                                                   double*, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetOptionInt(struct AdbcConnection*, const char*,
                                                int64_t*, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetStatistics(struct AdbcConnection*, const char*,
                                                 const char*, const char*, char,
                                                 struct ArrowArrayStream*,
                                                 struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetStatisticNames(struct AdbcConnection*,
                                                     struct ArrowArrayStream*,
                                                     struct AdbcError*);
AdbcStatusCode ClickHouseConnectionGetTableSchema(
    struct AdbcConnection* cnxn, const char* catalog, const char* dbSchema,
    const char* tableName, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionGetTableTypes(struct AdbcConnection* cnxn,
                                                 struct ArrowArrayStream* out,
                                                 struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionInit(struct AdbcConnection* cnxn,
                                        struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionNew(struct AdbcConnection* cnxn,
                                       struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionReadPartition(struct AdbcConnection* cnxn,
                                                 const uint8_t* serialized,
                                                 size_t serializedLen,
                                                 struct ArrowArrayStream* out,
                                                 struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionRelease(struct AdbcConnection* cnxn,
                                           struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionRollback(struct AdbcConnection* cnxn,
                                            struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionSetOption(struct AdbcConnection* cnxn, const char* key,
                                             const char* val, struct AdbcError* err);
AdbcStatusCode ClickHouseConnectionSetOptionBytes(struct AdbcConnection*, const char*,
                                                  const uint8_t*, size_t,
                                                  struct AdbcError*);
AdbcStatusCode ClickHouseConnectionSetOptionDouble(struct AdbcConnection*, const char*,
                                                   double, struct AdbcError*);
AdbcStatusCode ClickHouseConnectionSetOptionInt(struct AdbcConnection*, const char*,
                                                int64_t, struct AdbcError*);

AdbcStatusCode ClickHouseStatementBind(struct AdbcStatement* stmt,
                                       struct ArrowArray* values,
                                       struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode ClickHouseStatementBindStream(struct AdbcStatement* stmt,
                                             struct ArrowArrayStream* stream,
                                             struct AdbcError* err);
AdbcStatusCode ClickHouseStatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementExecuteQuery(struct AdbcStatement* stmt,
                                               struct ArrowArrayStream* out,
                                               int64_t* affected, struct AdbcError* err);
AdbcStatusCode ClickHouseStatementExecutePartitions(struct AdbcStatement* stmt,
                                                    struct ArrowSchema* schema,
                                                    struct AdbcPartitions* partitions,
                                                    int64_t* affected,
                                                    struct AdbcError* err);
AdbcStatusCode ClickHouseStatementExecuteSchema(struct AdbcStatement*,
                                                struct ArrowSchema*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementGetOption(struct AdbcStatement*, const char*, char*,
                                            size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementGetOptionBytes(struct AdbcStatement*, const char*,
                                                 uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementGetOptionDouble(struct AdbcStatement*, const char*,
                                                  double*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementGetOptionInt(struct AdbcStatement*, const char*,
                                               int64_t*, struct AdbcError*);
AdbcStatusCode ClickHouseStatementGetParameterSchema(struct AdbcStatement* stmt,
                                                     struct ArrowSchema* schema,
                                                     struct AdbcError* err);
AdbcStatusCode ClickHouseStatementNew(struct AdbcConnection* cnxn,
                                      struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode ClickHouseStatementPrepare(struct AdbcStatement* stmt,
                                          struct AdbcError* err);
AdbcStatusCode ClickHouseStatementRelease(struct AdbcStatement* stmt,
                                          struct AdbcError* err);
AdbcStatusCode ClickHouseStatementSetOption(struct AdbcStatement* stmt, const char* key,
                                            const char* value, struct AdbcError* err);
AdbcStatusCode ClickHouseStatementSetOptionBytes(struct AdbcStatement*, const char*,
                                                 const uint8_t*, size_t,
                                                 struct AdbcError*);
AdbcStatusCode ClickHouseStatementSetOptionDouble(struct AdbcStatement*, const char*,
                                                  double, struct AdbcError*);
AdbcStatusCode ClickHouseStatementSetOptionInt(struct AdbcStatement*, const char*,
                                               int64_t, struct AdbcError*);
AdbcStatusCode ClickHouseStatementSetSqlQuery(struct AdbcStatement* stmt,
                                              const char* query, struct AdbcError* err);
AdbcStatusCode ClickHouseStatementSetSubstraitPlan(struct AdbcStatement* stmt,
                                                   const uint8_t* plan, size_t length,
                                                   struct AdbcError* err);

AdbcStatusCode ClickHouseDriverInit(int version, void* rawDriver, struct AdbcError* err);

static inline void ClickHouseerrRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void ClickHouse_release_error(struct AdbcError* error);

struct ClickHouseError {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void ClickHouseReleaseErrWithDetails(struct AdbcError* error);

int ClickHouseErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail ClickHouseErrorGetDetail(const struct AdbcError* error, int index);

int ClickHouseArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream,
                                             struct ArrowSchema* out);
int ClickHouseArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream,
                                           struct ArrowArray* out);
