/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// targeting netstandard 2.x
#if(! NETSTANDARD2_0_OR_GREATER && ! NET6_0_OR_GREATER && ! NET472_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{

  public partial class TCancelOperationReq : TBase
  {
    private short _executionVersion;
    private bool _replacedByNextAttempt;

    public global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle OperationHandle { get; set; }

    public short ExecutionVersion
    {
      get
      {
        return _executionVersion;
      }
      set
      {
        __isset.executionVersion = true;
        this._executionVersion = value;
      }
    }

    public bool ReplacedByNextAttempt
    {
      get
      {
        return _replacedByNextAttempt;
      }
      set
      {
        __isset.replacedByNextAttempt = true;
        this._replacedByNextAttempt = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool executionVersion;
      public bool replacedByNextAttempt;
    }

    public TCancelOperationReq()
    {
    }

    public TCancelOperationReq(global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle operationHandle) : this()
    {
      this.OperationHandle = operationHandle;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_operationHandle = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                OperationHandle = new global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle();
                await OperationHandle.ReadAsync(iprot, cancellationToken);
                isset_operationHandle = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3329:
              if (field.Type == TType.I16)
              {
                ExecutionVersion = await iprot.ReadI16Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3330:
              if (field.Type == TType.Bool)
              {
                ReplacedByNextAttempt = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default:
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_operationHandle)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp531 = new TStruct("TCancelOperationReq");
        await oprot.WriteStructBeginAsync(tmp531, cancellationToken);
        var tmp532 = new TField();
        if((OperationHandle != null))
        {
          tmp532.Name = "operationHandle";
          tmp532.Type = TType.Struct;
          tmp532.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp532, cancellationToken);
          await OperationHandle.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.executionVersion)
        {
          tmp532.Name = "executionVersion";
          tmp532.Type = TType.I16;
          tmp532.ID = 3329;
          await oprot.WriteFieldBeginAsync(tmp532, cancellationToken);
          await oprot.WriteI16Async(ExecutionVersion, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.replacedByNextAttempt)
        {
          tmp532.Name = "replacedByNextAttempt";
          tmp532.Type = TType.Bool;
          tmp532.ID = 3330;
          await oprot.WriteFieldBeginAsync(tmp532, cancellationToken);
          await oprot.WriteBoolAsync(ReplacedByNextAttempt, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is TCancelOperationReq other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(OperationHandle, other.OperationHandle)
        && ((__isset.executionVersion == other.__isset.executionVersion) && ((!__isset.executionVersion) || (global::System.Object.Equals(ExecutionVersion, other.ExecutionVersion))))
        && ((__isset.replacedByNextAttempt == other.__isset.replacedByNextAttempt) && ((!__isset.replacedByNextAttempt) || (global::System.Object.Equals(ReplacedByNextAttempt, other.ReplacedByNextAttempt))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((OperationHandle != null))
        {
          hashcode = (hashcode * 397) + OperationHandle.GetHashCode();
        }
        if(__isset.executionVersion)
        {
          hashcode = (hashcode * 397) + ExecutionVersion.GetHashCode();
        }
        if(__isset.replacedByNextAttempt)
        {
          hashcode = (hashcode * 397) + ReplacedByNextAttempt.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp533 = new StringBuilder("TCancelOperationReq(");
      if((OperationHandle != null))
      {
        tmp533.Append(", OperationHandle: ");
        OperationHandle.ToString(tmp533);
      }
      if(__isset.executionVersion)
      {
        tmp533.Append(", ExecutionVersion: ");
        ExecutionVersion.ToString(tmp533);
      }
      if(__isset.replacedByNextAttempt)
      {
        tmp533.Append(", ReplacedByNextAttempt: ");
        ReplacedByNextAttempt.ToString(tmp533);
      }
      tmp533.Append(')');
      return tmp533.ToString();
    }
  }

}
