/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


// targeting netstandard 2.x
#if(! NETSTANDARD2_0_OR_GREATER && ! NET6_0_OR_GREATER && ! NET472_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{
  public static class TCLIServiceConstants
  {
    public static HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId> PRIMITIVE_TYPES = new HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId>();
    public static HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId> COMPLEX_TYPES = new HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId>();
    public static HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId> COLLECTION_TYPES = new HashSet<global::Apache.Hive.Service.Rpc.Thrift.TTypeId>();
    public static Dictionary<global::Apache.Hive.Service.Rpc.Thrift.TTypeId, string> TYPE_NAMES = new Dictionary<global::Apache.Hive.Service.Rpc.Thrift.TTypeId, string>();
    public const string CHARACTER_MAXIMUM_LENGTH = "characterMaximumLength";
    public const string PRECISION = "precision";
    public const string SCALE = "scale";
    static TCLIServiceConstants()
    {
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BOOLEAN_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TINYINT_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.SMALLINT_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INT_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BIGINT_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.FLOAT_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DOUBLE_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.STRING_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TIMESTAMP_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BINARY_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DECIMAL_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.NULL_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DATE_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.VARCHAR_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.CHAR_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INTERVAL_YEAR_MONTH_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INTERVAL_DAY_TIME_TYPE);
      PRIMITIVE_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TIMESTAMPLOCALTZ_TYPE);
      COMPLEX_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.ARRAY_TYPE);
      COMPLEX_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.MAP_TYPE);
      COMPLEX_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.STRUCT_TYPE);
      COMPLEX_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.UNION_TYPE);
      COMPLEX_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.USER_DEFINED_TYPE);
      COLLECTION_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.ARRAY_TYPE);
      COLLECTION_TYPES.Add(global::Apache.Hive.Service.Rpc.Thrift.TTypeId.MAP_TYPE);
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.ARRAY_TYPE] = "ARRAY";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BIGINT_TYPE] = "BIGINT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BINARY_TYPE] = "BINARY";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.BOOLEAN_TYPE] = "BOOLEAN";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.CHAR_TYPE] = "CHAR";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DATE_TYPE] = "DATE";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DECIMAL_TYPE] = "DECIMAL";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.DOUBLE_TYPE] = "DOUBLE";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.FLOAT_TYPE] = "FLOAT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INTERVAL_DAY_TIME_TYPE] = "INTERVAL_DAY_TIME";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INTERVAL_YEAR_MONTH_TYPE] = "INTERVAL_YEAR_MONTH";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.INT_TYPE] = "INT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.MAP_TYPE] = "MAP";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.NULL_TYPE] = "NULL";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.SMALLINT_TYPE] = "SMALLINT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.STRING_TYPE] = "STRING";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.STRUCT_TYPE] = "STRUCT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TIMESTAMPLOCALTZ_TYPE] = "TIMESTAMP WITH LOCAL TIME ZONE";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TIMESTAMP_TYPE] = "TIMESTAMP";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.TINYINT_TYPE] = "TINYINT";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.UNION_TYPE] = "UNIONTYPE";
      TYPE_NAMES[global::Apache.Hive.Service.Rpc.Thrift.TTypeId.VARCHAR_TYPE] = "VARCHAR";
    }
  }
}
