/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;


// targeting netstandard 2.x
#if(! NETSTANDARD2_0_OR_GREATER && ! NET6_0_OR_GREATER && ! NET472_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{
  internal static class TCLIServiceExtensions
  {
    public static bool Equals(this Dictionary<string, double> instance, object that)
    {
      if (!(that is Dictionary<string, double> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, double> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TDBSqlConfValue> instance, object that)
    {
      if (!(that is Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TDBSqlConfValue> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TDBSqlConfValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TTypeQualifierValue> instance, object that)
    {
      if (!(that is Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TTypeQualifierValue> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, global::Apache.Hive.Service.Rpc.Thrift.TTypeQualifierValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, int> instance, object that)
    {
      if (!(that is Dictionary<string, int> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, int> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this Dictionary<string, string> instance, object that)
    {
      if (!(that is Dictionary<string, string> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<List<string>> instance, object that)
    {
      if (!(that is List<List<string>> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<List<string>> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<bool> instance, object that)
    {
      if (!(that is List<bool> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<bool> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<byte[]> instance, object that)
    {
      if (!(that is List<byte[]> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<byte[]> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<double> instance, object that)
    {
      if (!(that is List<double> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<double> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumn> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TColumn> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumn> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumnDesc> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TColumnDesc> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumnDesc> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumnValue> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TColumnValue> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TColumnValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlCloudResultFile> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlCloudResultFile> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlCloudResultFile> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlStatement> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlStatement> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlStatement> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlTempView> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlTempView> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TDBSqlTempView> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TExpressionInfo> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TExpressionInfo> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TExpressionInfo> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoType> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoType> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoType> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoValue> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoValue> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TGetInfoValue> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TRow> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TRow> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TRow> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TSQLVariable> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TSQLVariable> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TSQLVariable> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowBatch> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowBatch> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowBatch> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowResultLink> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowResultLink> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkArrowResultLink> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameter> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameter> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameter> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameterValueArg> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameterValueArg> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TSparkParameterValueArg> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<global::Apache.Hive.Service.Rpc.Thrift.TTypeEntry> instance, object that)
    {
      if (!(that is List<global::Apache.Hive.Service.Rpc.Thrift.TTypeEntry> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Apache.Hive.Service.Rpc.Thrift.TTypeEntry> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<int> instance, object that)
    {
      if (!(that is List<int> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<int> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<long> instance, object that)
    {
      if (!(that is List<long> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<long> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<sbyte> instance, object that)
    {
      if (!(that is List<sbyte> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<sbyte> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<short> instance, object that)
    {
      if (!(that is List<short> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<short> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static bool Equals(this List<string> instance, object that)
    {
      if (!(that is List<string> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


  }
}
