/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.21.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


// targeting netstandard 2.x
#if(! NETSTANDARD2_0_OR_GREATER && ! NET6_0_OR_GREATER && ! NET472_OR_GREATER)
#error Unexpected target platform. See 'thrift --help' for details.
#endif

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable CS0618   // silence our own deprecation warnings
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{

  public partial class TGetOperationStatusReq : TBase
  {
    private bool _getProgressUpdate;
    private bool _getResultSetMetadataOnCompletion;
    private bool _getInlineResultSetOnCompletion;

    public global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle OperationHandle { get; set; }

    public bool GetProgressUpdate
    {
      get
      {
        return _getProgressUpdate;
      }
      set
      {
        __isset.getProgressUpdate = true;
        this._getProgressUpdate = value;
      }
    }

    public bool GetResultSetMetadataOnCompletion
    {
      get
      {
        return _getResultSetMetadataOnCompletion;
      }
      set
      {
        __isset.getResultSetMetadataOnCompletion = true;
        this._getResultSetMetadataOnCompletion = value;
      }
    }

    public bool GetInlineResultSetOnCompletion
    {
      get
      {
        return _getInlineResultSetOnCompletion;
      }
      set
      {
        __isset.getInlineResultSetOnCompletion = true;
        this._getInlineResultSetOnCompletion = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool getProgressUpdate;
      public bool getResultSetMetadataOnCompletion;
      public bool getInlineResultSetOnCompletion;
    }

    public TGetOperationStatusReq()
    {
    }

    public TGetOperationStatusReq(global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle operationHandle) : this()
    {
      this.OperationHandle = operationHandle;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_operationHandle = false;
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                OperationHandle = new global::Apache.Hive.Service.Rpc.Thrift.TOperationHandle();
                await OperationHandle.ReadAsync(iprot, cancellationToken);
                isset_operationHandle = true;
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                GetProgressUpdate = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3329:
              if (field.Type == TType.Bool)
              {
                GetResultSetMetadataOnCompletion = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3330:
              if (field.Type == TType.Bool)
              {
                GetInlineResultSetOnCompletion = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default:
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
        if (!isset_operationHandle)
        {
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        }
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp518 = new TStruct("TGetOperationStatusReq");
        await oprot.WriteStructBeginAsync(tmp518, cancellationToken);
        var tmp519 = new TField();
        if((OperationHandle != null))
        {
          tmp519.Name = "operationHandle";
          tmp519.Type = TType.Struct;
          tmp519.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp519, cancellationToken);
          await OperationHandle.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.getProgressUpdate)
        {
          tmp519.Name = "getProgressUpdate";
          tmp519.Type = TType.Bool;
          tmp519.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp519, cancellationToken);
          await oprot.WriteBoolAsync(GetProgressUpdate, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.getResultSetMetadataOnCompletion)
        {
          tmp519.Name = "getResultSetMetadataOnCompletion";
          tmp519.Type = TType.Bool;
          tmp519.ID = 3329;
          await oprot.WriteFieldBeginAsync(tmp519, cancellationToken);
          await oprot.WriteBoolAsync(GetResultSetMetadataOnCompletion, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.getInlineResultSetOnCompletion)
        {
          tmp519.Name = "getInlineResultSetOnCompletion";
          tmp519.Type = TType.Bool;
          tmp519.ID = 3330;
          await oprot.WriteFieldBeginAsync(tmp519, cancellationToken);
          await oprot.WriteBoolAsync(GetInlineResultSetOnCompletion, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is TGetOperationStatusReq other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return global::System.Object.Equals(OperationHandle, other.OperationHandle)
        && ((__isset.getProgressUpdate == other.__isset.getProgressUpdate) && ((!__isset.getProgressUpdate) || (global::System.Object.Equals(GetProgressUpdate, other.GetProgressUpdate))))
        && ((__isset.getResultSetMetadataOnCompletion == other.__isset.getResultSetMetadataOnCompletion) && ((!__isset.getResultSetMetadataOnCompletion) || (global::System.Object.Equals(GetResultSetMetadataOnCompletion, other.GetResultSetMetadataOnCompletion))))
        && ((__isset.getInlineResultSetOnCompletion == other.__isset.getInlineResultSetOnCompletion) && ((!__isset.getInlineResultSetOnCompletion) || (global::System.Object.Equals(GetInlineResultSetOnCompletion, other.GetInlineResultSetOnCompletion))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((OperationHandle != null))
        {
          hashcode = (hashcode * 397) + OperationHandle.GetHashCode();
        }
        if(__isset.getProgressUpdate)
        {
          hashcode = (hashcode * 397) + GetProgressUpdate.GetHashCode();
        }
        if(__isset.getResultSetMetadataOnCompletion)
        {
          hashcode = (hashcode * 397) + GetResultSetMetadataOnCompletion.GetHashCode();
        }
        if(__isset.getInlineResultSetOnCompletion)
        {
          hashcode = (hashcode * 397) + GetInlineResultSetOnCompletion.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp520 = new StringBuilder("TGetOperationStatusReq(");
      if((OperationHandle != null))
      {
        tmp520.Append(", OperationHandle: ");
        OperationHandle.ToString(tmp520);
      }
      if(__isset.getProgressUpdate)
      {
        tmp520.Append(", GetProgressUpdate: ");
        GetProgressUpdate.ToString(tmp520);
      }
      if(__isset.getResultSetMetadataOnCompletion)
      {
        tmp520.Append(", GetResultSetMetadataOnCompletion: ");
        GetResultSetMetadataOnCompletion.ToString(tmp520);
      }
      if(__isset.getInlineResultSetOnCompletion)
      {
        tmp520.Append(", GetInlineResultSetOnCompletion: ");
        GetInlineResultSetOnCompletion.ToString(tmp520);
      }
      tmp520.Append(')');
      return tmp520.ToString();
    }
  }

}
