/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.17.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Apache.Hive.Service.Rpc.Thrift
{
  public enum TProtocolVersion
  {
    HIVE_CLI_SERVICE_PROTOCOL_V1 = 0,
    HIVE_CLI_SERVICE_PROTOCOL_V2 = 1,
    HIVE_CLI_SERVICE_PROTOCOL_V3 = 2,
    HIVE_CLI_SERVICE_PROTOCOL_V4 = 3,
    HIVE_CLI_SERVICE_PROTOCOL_V5 = 4,
    HIVE_CLI_SERVICE_PROTOCOL_V6 = 5,
    HIVE_CLI_SERVICE_PROTOCOL_V7 = 6,
    HIVE_CLI_SERVICE_PROTOCOL_V8 = 7,
    HIVE_CLI_SERVICE_PROTOCOL_V9 = 8,
    HIVE_CLI_SERVICE_PROTOCOL_V10 = 9,
    HIVE_CLI_SERVICE_PROTOCOL_V11 = 10,
    SPARK_CLI_SERVICE_PROTOCOL_V1 = 42241,
    SPARK_CLI_SERVICE_PROTOCOL_V2 = 42242,
    SPARK_CLI_SERVICE_PROTOCOL_V3 = 42243,
    SPARK_CLI_SERVICE_PROTOCOL_V4 = 42244,
    SPARK_CLI_SERVICE_PROTOCOL_V5 = 42245,
    SPARK_CLI_SERVICE_PROTOCOL_V6 = 42246,
    SPARK_CLI_SERVICE_PROTOCOL_V7 = 42247,
  }
}
