# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""
Parse pg_type.dat and generate C++ code.
"""

import argparse
import ast
import dataclasses
import types
from pathlib import Path


@dataclasses.dataclass(frozen=True)
class PgTypeDef:
    oid: int
    typalign: str
    typbyval: str
    typcategory: str
    typinput: str
    typlen: str
    typname: str
    typoutput: str
    typreceive: str
    typsend: str
    descr: str = ""
    array_type_oid: int | None = None
    typanalyze: str | None = None
    typarray: str | None = None
    typcollation: str | None = None
    typdelim: str | None = None
    typelem: str | None = None
    typispreferred: str | None = None
    typmodin: str | None = None
    typmodout: str | None = None
    typrelid: str | None = None
    typstorage: str | None = None
    typsubscript: str | None = None
    typtype: str | None = None


template = """// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// !! DO NOT EDIT!!
// Auto-generated by pgtype.py.

#include "postgresql/postgres_type.h"

#include <nanoarrow/nanoarrow.hpp>

#include "driver/framework/status.h"

using adbc::driver::Status;

struct ArrowError;

namespace adbcpq {{

Status InitializeTypeResolver(PostgresTypeResolver& resolver) {{
  PostgresTypeResolver::Item type_item;
  type_item.class_oid = 0;
  type_item.base_oid = 0;
  ArrowError na_error = {{}};

{func_body}
  return Status::Ok();
}}

}}  // namespace adbcpq
"""  # noqa:E501


def parse(pgtypedat):
    # Not a real parser, just kitbashing
    lines = [(i + 1, line.strip()) for i, line in enumerate(pgtypedat.splitlines())]
    lines = [
        (lineno, line) for (lineno, line) in lines if line and not line.startswith("#")
    ]
    lines = [(lineno, line) for (lineno, line) in lines if line not in ("[", "]")]

    fields = {f.name: f for f in dataclasses.fields(PgTypeDef)}

    while lines:
        lineno, line = lines.pop(0)
        if not line.startswith("{"):
            raise ValueError(f"line {line:03}: expected '{{', got {line!r}")
        typedeflines = [line]
        while lines:
            if not lines:
                raise ValueError(f"line {lineno:03}: unexpected EOF")
            lineno, line = lines.pop(0)
            typedeflines.append(line)
            if line.endswith("},"):
                break

        typedeftext = " ".join(typedeflines)
        while True:
            pos = typedeftext.find("=>")
            if pos == -1:
                break
            while pos > 0 and typedeftext[pos - 1].isspace():
                pos -= 1
            end = pos
            while pos > 0 and not typedeftext[pos - 1].isspace():
                pos -= 1
            start = pos
            typedeftext = (
                typedeftext[:start]
                + "'"
                + typedeftext[start:end]
                + "'"
                + typedeftext[end:]
            )
            typedeftext = typedeftext.replace("=>", ":", 1)
        typedeftext = typedeftext.rstrip(",")
        parts = ast.literal_eval(typedeftext)

        # align the parts with the dataclass fields
        args = {}
        for k, v in parts.items():
            if k not in fields:
                raise ValueError(f"line {lineno:03}: unknown field {k!r}")
            f = fields[k]
            if f.type == int:  # noqa:E721
                v = int(v)
            elif isinstance(f.type, types.UnionType) and int in f.type.__args__:
                v = int(v)
            args[k] = v
        yield PgTypeDef(**args)


def generate(defs) -> str:
    lines = []
    for defn in defs:
        if defn.typrelid or defn.typarray:
            continue
        if defn.typreceive in ("", "-", "array_recv", "range_recv"):
            continue

        lines.append(f"  type_item.oid = {defn.oid};")
        lines.append(f'  type_item.typname = "{defn.typname}";')
        lines.append(f'  type_item.typreceive = "{defn.typreceive}";')
        lines.append("  type_item.child_oid = 0;")
        lines.append(
            "  UNWRAP_NANOARROW(na_error, Internal, "
            "resolver.Insert(type_item, &na_error));"
        )

        if defn.array_type_oid:
            lines.append(f"  type_item.oid = {defn.array_type_oid};")
            lines.append(f'  type_item.typname = "_{defn.typname}";')
            lines.append('  type_item.typreceive = "array_recv";')
            lines.append(f"  type_item.child_oid = {defn.oid};")
            lines.append(
                "  UNWRAP_NANOARROW(na_error, Internal, "
                "resolver.Insert(type_item, &na_error));"
            )

        lines.append("")

    return template.format(func_body="\n".join(lines)).strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("pgtypedat", type=Path, help="Path to pg_type.dat")
    args = parser.parse_args()

    with args.pgtypedat.open() as f:
        defs = list(parse(f.read()))

    print(generate(defs))


if __name__ == "__main__":
    main()
