# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Native Libraries (Unix)

on:
  pull_request:
    branches:
      - main
    paths:
      - "adbc.h"
      - "c/**"
      - "ci/**"
      - "docs/**"
      - "glib/**"
      - "go/**"
      - "python/**"
      - "r/**"
      - "ruby/**"
      - ".github/workflows/native-unix.yml"
  push:
    paths:
      - "adbc.h"
      - "c/**"
      - "ci/**"
      - "docs/**"
      - "glib/**"
      - "go/**"
      - "python/**"
      - "r/**"
      - "ruby/**"
      - ".github/workflows/native-unix.yml"

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Increment this to reset cache manually
  CACHE_NUMBER: "1"

jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [11, 12, 13, 14, 15]
        fail-fast: false
    name: "PostgreSQL Version ${{ matrix.pg_version }}"
    services:
      postgres:
        image: postgres:${{ matrix.pg_version }}
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get Date
        id: get-date
        shell: bash
        run: |
          echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Cache Conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/**') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-only-tar-bz2: false
          use-mamba: true
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge \
            --file ci/conda_env_cpp.txt
      - name: Build PostgreSQL Driver
        shell: bash -l {0}
        run: |
          env BUILD_ALL=0 BUILD_DRIVER_POSTGRESQL=1 ./ci/scripts/cpp_build.sh "$(pwd)" "$(pwd)/build"
      - name: Test PostgreSQL Driver
        shell: bash -l {0}
        env:
          ADBC_POSTGRESQL_TEST_URI: "postgres://localhost:5432/postgres?user=postgres&password=password"
        run: |
          env BUILD_ALL=0 BUILD_DRIVER_POSTGRESQL=1 ./ci/scripts/cpp_test.sh "$(pwd)/build"
