# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: R

on:
  pull_request:
    branches:
      - main
    paths:
      - "adbc.h"
      - "c/**"
      - "go/adbc/driver/**"
      - "go/adbc/pkg/**"
      - "r/**"
      - ".github/workflows/r.yml"

  push:
    paths:
      - "adbc.h"
      - "c/**"
      - "go/adbc/driver/**"
      - "go/adbc/pkg/**"
      - "r/**"
      - ".github/workflows/r.yml"

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  r-release:
    name: "${{ matrix.pkg }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [macOS, windows, ubuntu]
        pkg: [adbcdrivermanager, adbcsqlite, adbcpostgresql, adbcflightsql, adbcsnowflake]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - name: Set PKG_CONFIG_PATH on MacOS
        if: matrix.pkg == 'adbcpostgresql' && runner.os == 'macOS'
        run: |
          PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(brew --prefix libpq)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig"
          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}" >> $GITHUB_ENV

      - name: Run bootstrap.R
        if: matrix.pkg != 'adbcdrivermanager'
        run: |
          cd r/${{ matrix.pkg }}
          Rscript bootstrap.R
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, local::../adbcdrivermanager
          needs: check
          working-directory: r/${{ matrix.pkg }}

      - name: Start postgres test database
        if: matrix.pkg == 'adbcpostgresql' && runner.os == 'Linux'
        run: |
          cd r/adbcpostgresql
          docker compose up --detach postgres-test
          ADBC_POSTGRESQL_TEST_URI="postgresql://localhost:5432/postgres?user=postgres&password=password"
          echo "ADBC_POSTGRESQL_TEST_URI=${ADBC_POSTGRESQL_TEST_URI}" >> $GITHUB_ENV

      - name: Start FlightSQL test database
        if: matrix.pkg == 'adbcflightsql' && runner.os == 'Linux'
        run: |
          cd r/adbcpostgresql
          docker compose up --detach flightsql-sqlite-test
          ADBC_FLIGHTSQL_TEST_URI="grpc://localhost:8080"
          echo "ADBC_FLIGHTSQL_TEST_URI=${ADBC_FLIGHTSQL_TEST_URI}" >> $GITHUB_ENV

      - uses: r-lib/actions/check-r-package@v2
        env:
          ADBC_SNOWFLAKE_TEST_URI: ${{ secrets.SNOWFLAKE_URI }}
        with:
          upload-snapshots: true
          working-directory: r/${{ matrix.pkg }}

      - name: Shutdown docker compose services
        if: runner.os == 'Linux'
        run: |
          docker compose down
